### PR TITLE
FIR compatibility update

### PR DESCRIPTION
**Pull request by mgkid3310**
TBD: aircraft-specific features on/off update

There's many more aircrafts to work on and need aircraft-specific configs updated, but this might be a good start for further work.

### CODE REVIEW

**Comment by mgkid3310** [comment]
Is there a documentation for each "mfdApps" and "systems"? I couldn't find witch does what for some of them.

Note: F-15C/D has TGP turned off (E has TGP on).

**Comment by YannikH** [comment]
Thanks for the contribution, but compats are handled as standalone addons, as I would like to avoid making any dependencies on FIR content.

The repository for the compatibility addons can be found here 
https://github.com/itc-addons/itc_air_compats

The steam workshop collection for the compatibility addons can be found here
https://steamcommunity.com/sharedfiles/filedetails/?id=1501767670

The most recent docs on the systems and apps can be found here
https://github.com/YannikH/itc_air/wiki/Compatibility

**Comment by mgkid3310** [comment]
Oh, thanks. I didn't notice the compat rep. Thanks again for the help, shall I close this PR?

**Comment by mgkid3310** [comment]
BTW, do you have any plans to gather all the compat addons to a single addons? Since ITC properties don't conflict with plane's base configs, I don't see the need to separate addons.

**Comment by YannikH** [comment]
I did plan to release it as a single workshop item with everything in it, but I simply haven't really been focussing on compats lately.

If you can make your additions a PR for the compat repo I'll make sure to include it all and get it on the workshop!

**Pull request closed without merging**
